# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: mv-hub-api deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: echo "DB_URI=${{ secrets.DB_URI }}" >> .env

      - name: Start API server
        run: npm start

  
